### ISSUE TITLE
--bind option not working

### ISSUE THREAD

**Issue by picojulien** [troglobit/redir#17]
Hi there,

I might use the `--bind` option in an inappropriate way, but from the manual I understand that you can ensure that bind is listening on a given interface by specifying `--bind=X.X.X.X` where X.X.X.X is the ip from which you want to receive the incoming connections.

However, when I do 

`redir --bind=X.X.X.X :1234 localhost 1234`

redir seems to listen on any interfaces (netstat list redir with `0.0.0.0:1234` local address), wheras if I do 

`redir X.X.X.X:1234 localhost 1234`

redir seems to listen on X.X.X.X only (netstat list redir with `X.X.X.X:1234` local address)

It seems that: 

1. bind option does not work properly
2. the bind effect can be obtained by specifying  the listening address (without bind option)

Thanks for this very useful piece of software anyway !

**Comment by troglobit** [comment]
Must be a regression from when the new syntax was introduced. Likely a simple fix. Care to give it a try and submit a PR?

**Comment by troglobit** [comment]
So, turns out this was just poorly documented.  The `--bind=ADDR` option is only for limiting the interfaces (addresses) redir listens to responses from the server side (DST:PORT).

I've updated the docs, including the manual page: https://man.troglobit.com/man1/redir.1.html

Hopefully this clarifies things.
