### ISSUE TITLE
should not daemonize by default

### ISSUE THREAD

**Issue by rofl0r** [troglobit/redir#2]
this program traditionally was a tiny helper program and simple in the unix sense of "do one thing and do it well", so it just did the work and behaved like unix programs usually do: i.e. it stays in the foreground and prints errors to stderr and other stuff to stdout.
you've changed that to daemonize by default and log to syslog by default, which violates the principle of least surprise a lot. as noted in #1 if you make a mistake in the syntax or some other error happens, by default you dont get any output - it just seems to the user that the program doesn't work. if you really want to keep these features in redir, you should at least make them optional. currently, i am not really happy about how this fork behaves and consider switching back to the original.

**Comment by troglobit** [comment]
You are more than welcome to switch back to the original, or fork it yourself if you think you can add value.

I have no plans of changing the new defaults. which were introduced in a new major version to make a clear separation between it and the original.  The new defaults make headless server and embedded systems a first class citizen, where syslog is the preferred way rather than stdout.

On an additional note, it is not my job to keep every user happy.  I don't get paid for that.

**Comment by rofl0r** [comment]
well, i guess i just can't see the point of becoming maintainer of an abandoned project to then just confuse its users by swapping out the entire interface. all of your added default behaviour is usually done with a specific external tool and doesn't need to be baked in (reminds me of systemd).

**Comment by troglobit** [comment]
Nobody is forcing you to use my software. If you dislike the direction I've
taken, so be it. I've long since accepted that you cannot make everyone
happy.

The great thing with open source and free software, however, is that if you
don't like it you can fork it and fix it.

Now, it's up to you, but I'd recommend being a bit more respectful in your
contact with other maintainers. Being rude and disrespectful will not bring
you any favors. I for one will not engage with you again.

Best Regards
/Joachim
